In [11]:
 # Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
from us import states
import requests
import json
#import gmaps

# Census API Key
from config import api_key

c = Census(api_key, year=2021)

#gmaps.configure(api_key=gkey)
#print(bls_key)

In [11]:
# Run search to retrieve data
census_data = c.acs1.get(("NAME", "B01003_001E", "B19301_001E", "C17002_001E",
                          "B25077_001E"), {'for': 'state:*'})
# params = {
#     "K200104_001E",
#     "K201901_001E",
#     "K201702_001E",
#     "K202510_001E",
#     "STATE"
# }

#url = f"https://api.census.gov/data/2021/acs/acs1?get=NAME,B01001_001E&for=state:*&key={api_key}"
#census_data = requests.get(url)
#census_json = census_data.json()
# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B19301_001E": "Household Income",
                                      "C17002_001E": "Ratio of Income to Poverty Level",
                                      "B25077_001E": "Median Value",
                                      "NAME": "Name", "state": "State"})

census_pd.head()

,Name,Population,Household Income,Ratio of Income to Poverty Level,Median Value,State
0,Alabama,5039877.0,30608.0,4920613.0,172800.0,01
1,Puerto Rico,3263584.0,14468.0,3235303.0,114100.0,72
2,Arizona,7276316.0,36295.0,7126930.0,336300.0,04
3,Arkansas,3025891.0,29252.0,2944289.0,162300.0,05
4,California,39237836.0,42396.0,38481790.0,648100.0,06

In [12]:
census_pd.to_csv("census_data.csv", encoding="utf-8", index=False)

In [15]:
census_data_more = c.acs1.get(("NAME", "B01003_001E", "B19001_001E", "B19013_001E", 
                            "B19313_001E",
                            "B19025_001E",
                            "C17002_001E",
                            "B25077_001E",
                            "B19051_001E",
                            "B19052_001E",
                            "B19053_001E",
                            "B19054_001E",
                            "B19055_001E",
                            "B19056_001E",
                            "B19057_001E",
                            "B19058_001E",
                            "B19059_001E",
                            "B19060_001E",
                            "B19062_001E",
                            "B25075_001E",
                            "B25094_001E",
                            "B25104_001E"), {'for': 'state:*'})


# Convert to DataFrame
census_more_pd = pd.DataFrame(census_data_more)

# Column Reordering
census_more_pd = census_more_pd.rename(columns={"B01003_001E": "Population",
                                      "B19301_001E": "Household Income",
                                      "B19013_001E": "Median Household Income",
                                      "B19313_001E": "Aggregate Income",
                                      "B19025_001E": "Aggregate Household Income",
                                      "C17002_001E": "Ratio of Income to Poverty Level",
                                      "B25077_001E": "Median Value",
                                      "B19051_001E": "Earnings",
                                      "B19052_001E": "Wage or Salary Income",
                                      "B19053_001E": "Self-Employed Income",
                                      "B19054_001E": "Interest, Dividend, or Net Rental Income",
                                      "B19055_001E": "Social Security Income",
                                      "B19056_001E": "Supplemental Income",
                                      "B19057_001E": "Public Assistance Income",
                                      "B19058_001E": "Public Assistance or Food Stamp/SNAP Income",
                                      "B19059_001E": "Retirement Income",
                                      "B19060_001E": "Other Types of Income",
                                      "B19062_001E": "Aggregate Earnings for Households",
                                      "B25075_001E": "Value",
                                      "B25094_001E": "Selected Monthly Owner Costs",
                                      "B25104_001E": "Monthly Housing Costs",
                                      "NAME": "Name", "state": "State"})

census_more_pd.head()

,Name,Population,B19001_001E,Median Household Income,Aggregate Income,Aggregate Household Income,Ratio of Income to Poverty Level,Median Value,Earnings,Wage or Salary Income,...,Supplemental Income,Public Assistance Income,Public Assistance or Food Stamp/SNAP Income,Retirement Income,Other Types of Income,Aggregate Earnings for Households,Value,Selected Monthly Owner Costs,Monthly Housing Costs,State
0,Alabama,5039877.0,1967559.0,53913.0,1.542611e+11,1.493825e+11,4920613.0,172800.0,1967559.0,1967559.0,...,1967559.0,1967559.0,1967559.0,1967559.0,1967559.0,1.061057e+11,1377932.0,1377932.0,1967559.0,01
1,Puerto Rico,3263584.0,1165982.0,22237.0,4.721860e+10,4.133695e+10,3235303.0,114100.0,1165982.0,1165982.0,...,1165982.0,1165982.0,1165982.0,1165982.0,1165982.0,2.413150e+10,800555.0,800555.0,1165982.0,72
2,Arizona,7276316.0,2817723.0,69056.0,2.640942e+11,2.625475e+11,7126930.0,336300.0,2817723.0,2817723.0,...,2817723.0,2817723.0,2817723.0,2817723.0,2817723.0,1.856334e+11,1905690.0,1905690.0,2817723.0,04
3,Arkansas,3025891.0,1183675.0,52528.0,8.851379e+10,8.655705e+10,2944289.0,162300.0,1183675.0,1183675.0,...,1183675.0,1183675.0,1183675.0,1183675.0,1183675.0,6.107493e+10,793038.0,793038.0,1183675.0,05
4,California,39237836.0,13429063.0,84907.0,1.663512e+12,1.624283e+12,38481790.0,648100.0,13429063.0,13429063.0,...,13429063.0,13429063.0,13429063.0,13429063.0,13429063.0,1.214226e+12,7502706.0,7502706.0,13429063.0,06

In [16]:
census_more_pd.to_csv("census_data_more.csv", encoding="utf-8", index=False)